# Generated by Django 4.2.1 on 2023-07-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loginusers_day_shift_loginusers_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTicks',
        ),
        migrations.RenameField(
            model_name='loginusers',
            old_name='project_no',
            new_name='client',
        ),
        migrations.AddField(
            model_name='loginusers',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='current',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='metsys_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='satpic',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='vessel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='wave',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='loginusers',
            name='wind',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
