# Generated by Django 4.2.1 on 2023-07-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_userticks_rename_project_no_loginusers_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusers',
            name='forecast_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
