# Generated by Django 4.2.1 on 2023-07-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loginusers_forecast_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='operation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
