# Generated by Django 4.2.1 on 2023-07-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatrooms_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
