# Generated by Django 4.2.1 on 2023-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='unread_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatrooms',
            name='unread_user',
            field=models.IntegerField(default=0),
        ),
    ]
