# Generated by Django 4.2.1 on 2023-10-01 09:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_name_chat_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='imgfile',
            field=models.CharField(default=' ', max_length=10240),
        ),
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, upload_to=api.models.upload_to),
        ),
    ]
