# Generated by Django 4.2.1 on 2023-10-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chat_imgfile_alter_chat_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='imgfile',
        ),
    ]
